export const FETCH_POKEMON_LIST: string = 'FETCH_POKEMON_LIST';
export const FETCH_POKEMON_LIST_SUCCESS: string = 'FETCH_POKEMON_LIST_SUCCESS';
export const FETCH_POKEMON_LIST_FAILED: string = 'FETCH_POKEMON_LIST_FAILED';

export const FILTER_POKEMON_LIST: string = 'FILTER_POKEMON_LIST';
