export const FAVORITE_TOGGLED: string = 'FAVORITE_TOGGLED';

export const FETCH_MORE_DETAILS: string = 'FETCH_MORE_DETAILS';
export const FETCH_MORE_DETAILS_SUCCESS: string = 'FETCH_MORE_DETAILS_SUCCESS';
export const FETCH_MORE_DETAILS_FAILED: string = 'FETCH_MORE_DETAILS_FAILED';
