export const FETCH_MORE_DETAILS: string = 'FETCH_MORE_DETAILS';
export const FETCH_MORE_DETAILS_SUCCESS: string = 'FETCH_MORE_DETAILS_SUCCESS';
export const FETCH_MORE_DETAILS_FAILED: string = 'FETCH_MORE_DETAILS_FAILED';

export const FETCH_POKEMON_LIST: string = 'FETCH_POKEMON_LIST';
export const FETCH_POKEMON_LIST_SUCCESS: string = 'FETCH_POKEMON_LIST_SUCCESS';
export const FETCH_POKEMON_LIST_FAILED: string = 'FETCH_POKEMON_LIST_FAILED';

export const FILTER_POKEMON_LIST: string = 'FILTER_POKEMON_LIST';
